name: build-and-deploy-staging

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: iamqbao/gau_upload_service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass


      - name: Download .env from server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/tnqbao/.enviroment/gau-upload-service/staging.env ./deploy/k8s/staging/.env

      - name: Download kubeconfig.yaml from server
        run: |
          mkdir -p ./deploy/k8s/staging
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/.secret/k8s/kubeconfig.yaml ./deploy/k8s/staging/kubeconfig.yaml

      - name: Set KUBECONFIG environment variable
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/deploy/k8s/staging/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Check Kubernetes access
        run: kubectl get nodes

      - name: Make scripts executable
        run: |
          chmod +x ./deploy/k8s/staging/apply.sh

      - name: Apply manifests to Kubernetes
        working-directory: ./deploy/k8s/staging
        run: ./apply.sh

      - name: Check active pods
        run: kubectl get pods -n bao-staging-env

      - name: Restart pods
        run: |
          kubectl rollout restart deployment gau-upload-deployment -n bao-staging-env
          sleep 10
          kubectl get pods -n bao-staging-env
